// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClrW73yQau31IQgPUuZ27J2-BAugIZO44',
    appId: '1:787867647060:android:3aa61ca027ea0f741a81c1',
    messagingSenderId: '787867647060',
    projectId: 'ai-weather-f3421',
    storageBucket: 'ai-weather-f3421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9XNyEwQoJnx_S8OhVsmOq0hLam9patV0',
    appId: '1:787867647060:ios:fa39178b46bfd65b1a81c1',
    messagingSenderId: '787867647060',
    projectId: 'ai-weather-f3421',
    storageBucket: 'ai-weather-f3421.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8YMldBepQYilw1Rwu_g-OUgnGzOBqU5o',
    appId: '1:787867647060:web:55fc7fb4e2dc92541a81c1',
    messagingSenderId: '787867647060',
    projectId: 'ai-weather-f3421',
    authDomain: 'ai-weather-f3421.firebaseapp.com',
    storageBucket: 'ai-weather-f3421.firebasestorage.app',
    measurementId: 'G-3QQG6PPQN7',
  );
}
